spring:
  application:
    name: learn
  datasource:
    url: jdbc:postgresql://localhost:5432/buymycar
    username: postgres
    password: Root@023
    driver-class-name: org.postgresql.Driver
#      url: jdbc:mysql://buyacar.cx6iecm6icvj.ap-southeast-2.rds.amazonaws.com:3306/buymycar
#      username: buyacar
#      password: buyacar023
#      driver-class-name: org.mysql.Driver

  jpa:
    hibernate:
      ddl-auto: update # or "create", "create-drop", "validate", "none"
    show-sql: true
    properties:
      hibernate:
      format_sql: true
  security:
    user:
      name: admin
      password: Admin@123

